### ISSUE TITLE
Sphinx3.0.0でビルドエラーになる

### ISSUE THREAD

**Issue by zatsuyooo** [tk0miya/sphinxcontrib-toc#1]
## 問題
`Sphinx3.0.0`で`sphinx-build`を行うと下記エラーが発生する。

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/local/lib/python3.8/site-packages/sphinx/application.py", line 244, in __init__
    self.setup_extension(extension)
  File "/usr/local/lib/python3.8/site-packages/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/local/lib/python3.8/site-packages/sphinx/registry.py", line 414, in load_extension
    metadata = setup(app)
  File "/usr/local/lib/python3.8/site-packages/sphinxcontrib/toc.py", line 74, in setup
    app.add_source_parser('.toc', TableOfContentsParser)
  File "/usr/local/lib/python3.8/site-packages/sphinx/application.py", line 1069, in add_source_parser
    self.registry.add_source_parser(*args, **kwargs)
TypeError: add_source_parser() takes 2 positional arguments but 3 were given
```

## 期待する動作
ビルドエラーにならないこと。

## 環境
Python Version : 3.8.2 (from Docker Image `python:3-alpine`)
Sphinx Version : 3.0.0

**Comment by tk0miya** [comment]
Fixed and bump a new package!

(修正して新バージョンをリリースしました)
